package:
  name: pyocct
  version: 7.4.0.0

source:
  path: ../..

build:
  number: 0
  string: py{{ CONDA_PY }}

requirements:
  build:
    - {{ compiler('cxx') }} # [not linux]
    - cmake
    - ninja
    - pybind11
    - python-clang ==10.0.0
    - clang ==10.0.0
    - python
    - tbb-devel
    - occt ==7.4.0
    - smesh ==8.3.0.3

  run:
    - python
    - occt ==7.4.0
    - smesh ==8.3.0.3

test:
  requires:
    - pytest
  source_files:
    - test
  commands:
    - pytest test -v

about:
  home: https://github.com/LaughlinResearch/pyOCCT
  license: LGPL2.1
  license_family: LGPL
  summary: Python bindings for OpenCASCADE
  description: Python bindings for OpenCASCADE geometry kernel
               and SMESH meshing library.
