package:
  name: pyocct
  version: "7.4.0.0"

source:
  path: ../..

build:
  number: 0
  features:
    - vc17 # [win]

requirements:
  build:
    - python
    - vc 17 # [win]
    - cmake
    - ninja
    - pybind11==2.5.0
    - libclang==10.0.0
    - clang==10.0.0
    - occt==7.4.0
    - tbb-devel
    - libxcb # [linux]

  run:
    - python
    # - wxpython
    # - pyqt >=5
    - vc 17 # [win]
    - occt==7.4.0

test:
  source_files:
    - test

about:
  home: https://github.com/LaughlinResearch/pyOCCT
  license: LGPL2.1
  license_family: LGPL
  summary: Python bindings for OpenCASCADE
  description: Python bindings for OpenCASCADE geometry kernel
               and SMESH meshing library.
