# Sets the build environment.
sudo: required
dist: bionic

language: cpp
matrix:
  include:
    #- env: PYTHON_VERSION="3.6"
      #os: linux
      #dist: bionic
    - env: PYTHON_VERSION="3.7"
      os: linux
      dist: bionic

before_install:
  - sudo apt -q update
  - sudo apt -y install libxi-dev libgl1-mesa-dev

  # Install minconda
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$HOME/miniconda/lib:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda install python=$PYTHON_VERSION conda-build anaconda-client conda-verify
  - conda config --add channels conda-forge

script:
  - conda build ci/conda

after_success:
  - anaconda -t $CONDA_UPLOAD_TOKEN upload $HOME/miniconda/conda-bld/linux-64/pyocct*.bz2 -l $TRAVIS_BRANCH --force
