version: 7.4.0.0.{build}

image:
    - Visual Studio 2017
    - Ubuntu

environment:
  matrix:
    # https://www.appveyor.com/docs/windows-images-software/#python
    - MINICONDA: C:\Miniconda37-x64
      PYTHON_VERSION: 3.7

platform:
  - x64

install:
  - cmd: rmdir C:\cygwin /s /q
  - cmd: rmdir C:\QT /s /q
  - cmd: rmdir C:\MSYS64 /s /q
  - cmd: call %MINICONDA%\Scripts\activate.bat
  - cmd: conda.exe update --yes --quiet conda
  - cmd: conda.exe install conda-build conda-verify --yes
  - cmd: conda.exe config --set show_channel_urls true
  - cmd: conda.exe config --add channels conda-forge


  #- sh: sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  #- sh: sudo apt-get -q update
  #- sh: sudo apt-get -y install libxi-dev libgl1-mesa-dev

  - sh: wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - sh: chmod +x miniconda.sh
  - sh: bash miniconda.sh -b -p $HOME/miniconda
  - sh: export PATH="$HOME/miniconda/bin:$HOME/miniconda/lib:$PATH"
  - sh: conda config --set always_yes yes --set changeps1 no
  - sh: conda update -q conda
  - sh: conda install python=$PYTHON_VERSION conda-build conda-verify
  - sh: conda config --add channels conda-forge

build: off

test_script:
  - cmd: conda.exe build ci\conda
  - cmd: mkdir dist
  - cmd: copy %MINICONDA%\conda-bld\win-64\pyocct*.bz2 dist

  - sh: conda build ci/conda
  - sh: mkdir dist
  - sh: cp $HOME/miniconda/conda-bld/linux-64/pyocct*.bz2 dist

artifacts:
- path: dist\*
