on:
  push:
    branches:
    - '*'
  #pull_request:
  #  branches:
  #  - '*'
jobs:
  build:
    name: Build (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ['3.6']
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Remove system compilers
        if: matrix.os == 'windows-latest'
        shell: bash -l {0}
        run: |
           rm -Rf C:/ProgramData/chocolatey
           rm -Rf C:/Strawberry
      - name: Install OpenGL
        if: matrix.os == 'ubuntu-latest'
        run: |
            sudo apt update
            sudo apt -q -y install libglu1-mesa-dev libgl1-mesa-dev libxi-dev
      - name: Configure conda
        run: |
            conda info
            conda config --add channels conda-forge
      - name: Install conda-build
        run: |
            conda install python=${{ matrix.python-version }} conda-build conda-verify
      - name: Build
        shell: bash -l {0}
        run: |
            conda build ci/conda
