name: Conda Package
on:
  push:
    branches:
    - '*'
  #pull_request:
  #  branches:
  #  - '*'
jobs:
  build:
    name: Build (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ['3.6']
    steps:
      - name: "Clone pyOCCT"
        uses: actions/checkout@v2

      - name: "Install miniconda"
        uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: "Install g++ 10"
        if: matrix.os == 'ubuntu-latest'
        run: |
            sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
            sudo apt update
            sudo apt -q -y install g++-10
            sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 90 --slave /usr/bin/g++ g++ /usr/bin/g++-10 --slave /usr/bin/gcov gcov /usr/bin/gcov-10
      - name: "Configure conda"
        run: |
            conda info
            conda config --add channels conda-forge
      - name: "Install conda-build"
        run: |
            conda install python=${{ matrix.python-version }} conda-build conda-verify
      - name: "Build"
        shell: bash -l {0}
        run: |
            mkdir ci/dist/
            conda build ci/conda --no-test --output-folder ci/dist/
      - name: "Upload package"
        uses: actions/upload-artifact@v1
        with:
            name: Built Package
            path: ci/dist
      - name: "Run tests"
        shell: bash -l {0}
        run: |
            conda build ci/dist/*/pyocct-*.tar.bz2 --test --keep-going
